# Generated by Django 4.2.2 on 2023-07-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('review', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('albumCover', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
