# Generated by Django 4.2.2 on 2023-07-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.CharField(choices=[('uno', '1'), ('dos', '2'), ('tres', '3'), ('cuatro', '4'), ('cinco', '5'), ('seis', '6'), ('siete', '7'), ('ocho', '8'), ('nueve', '9'), ('diez', '10')], default='uno', max_length=10),
        ),
    ]
